apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bookinfo
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          env: "prod"
  template:
    metadata:
      name: '{{name}}-bookinfo'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/knee-berts/multi-cluster-gke-argocd/
        targetRevision: HEAD
        path: teams/team-2
      destination:
        server: '{{server}}' # 'server' field of the secret
        namespace: bookinfo
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
      ignoreDifferences:
      - group: networking.istio.io
        kind: VirtualService
        jsonPointers:
        - /spec/http/0
