apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-root
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: apps
    repoURL: 'https://github.com/knee-berts/multi-cluster-gke-argocd'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true