apiVersion: batch/v1
kind: Job
metadata:
  name: load-test
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: load-tester
        image: argoproj/load-tester:latest
        command: [sh, -c, -x, -e]
        args:
        - |
          wrk -t10 -c40 -d2h -s report.lua https://frontend.endpoints.argo-sp.cloud.goog/
          jq -e '.errors_ratio <= 0.05 and .latency_avg_ms < 100' report.json