apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-cluster-root
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cluster-config
    repoURL: https://github.com/knee-berts/multi-cluster-gke-argocd
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true