apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app: team-1-app-1
    istio.io/rev: asm-managed
  name: team-1-app-1
---
apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    app: team-1-app-1
  name: team-1-app-1-quota
  namespace: team-1-app-1
spec:
  hard:
    cpu: "1000"
    memory: 100Gi
    pods: "100"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: team-1-app-1
  name: team-1-app-1-rolebinding
  namespace: team-1-app-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edit
subjects:
- kind: Group
  name: team-1@nickeberts.altostrat.com
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: team-1-app-1
  name: team-1-app-1-canary
  namespace: team-1-app-1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: team-1-app-1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: team-1-app-1
  name: team-1-app-1-stable
  namespace: team-1-app-1
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: team-1-app-1
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: team-1-app-1
  name: team-1-app-1-rollout
  namespace: team-1-app-1
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: team-1-app-1
  strategy:
    canary:
      canaryService: team-1-app-1-canary
      stableService: team-1-app-1-stable
      steps:
      - setWeight: 20
      - pause:
          duration: 4m
      - analysis:
          args:
          - name: service-name
            value: team-1-app-1-canary.team-1-app-1.svc.cluster.local
          templates:
          - clusterScope: true
            templateName: success-rate
      - setWeight: 80
      - pause:
          duration: 4m
      - analysis:
          args:
          - name: service-name
            value: team-1-app-1-canary.team-1-app-1.svc.cluster.local
          templates:
          - clusterScope: true
            templateName: success-rate
      trafficRouting:
        istio:
          virtualServices:
          - name: virtualservice
            routes:
            - primary
  template:
    metadata:
      labels:
        app: team-1-app-1
        istio-injection: enabled
    spec:
      containers:
      - image: gcr.io/google-samples/whereami:v1.2.6
        name: team-1-app-1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 5m
            memory: 32Mi
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: team-1-app-1
  name: team-1-app-1-virtualservice
  namespace: team-1-app-1
spec:
  gateways:
  - asm-gateways/asm-ingress-gateway-xlb
  hosts:
  - hostname.local
  http:
  - name: primary
    route:
    - destination:
        host: team-1-app-1-stable
        port:
          number: 80
      weight: 100
    - destination:
        host: team-1-app-1-canary
        port:
          number: 80
      weight: 0
