apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    successCondition: result[0] >= 0.95
    provider:
      prometheus:
        address: "http://prometheus-frontend.prod-tools.svc.cluster.local:9090"
        query: |
          count(rate(
            istio_io:service_client_request_count{monitored_resource="istio_canonical_service",destination_service_name=~"rollouts-demo-canary",metric_response_code!~"5.*"}[1m]
          )) /
          count(rate(
            istio_io:service_client_request_count{monitored_resource="istio_canonical_service",destination_service_name=~"rollouts-demo-canary"}[1m]
          ))