apiVersion: networking.gke.io/v1beta1
kind: MultiClusterService
metadata:
  name: asm-ingressgateway-xlb-multicluster-svc
  namespace: asm-gateways
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"asm-ingress-xlb-config"}}'
    networking.gke.io/app-protocols: '{"http2":"HTTP2"}'
spec:
  template:
    spec:
      selector:
        istio: ingressgateway-xlb
      ports:
      - name: http2
        protocol: TCP
        port: 80 # Port the Service listens on
  clusters:
  - link: "us-central1-c/gke-std-1"
  - link: "us-east1/gke-ap-01"
