apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-1-app-generator
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/knee-berts/multi-cluster-gke-argocd/
              revision: HEAD
              directories:
                - path: teams/team-1/*
          - clusters:
              selector:
                matchLabels:
                  region: "us-east1"
  template:
    metadata:
      name: '{{name}}-{{path.basename}}'
    spec:
      project: "team-1"
      source:
        repoURL: https://github.com/knee-berts/multi-cluster-gke-argocd/
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}' # 'server' field of the secret
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 20
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m
      ignoreDifferences:
      - group: networking.istio.io
        kind: VirtualService
        jsonPointers:
        - /spec/http/0
