apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters: {}
  # - clusters:
  #     selector:
  #       matchLabels:
  #         region: "us-east1"
  template:
    metadata:
      name: '{{name}}-guestbook'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/knee-berts/multi-cluster-gke-argocd/
        targetRevision: HEAD
        path: apps/guestbook
      destination:
        server: '{{server}}' # 'server' field of the secret
        namespace: guestbook
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    allowEmpty: true
  syncOptions:
    - CreateNamespace=true
