apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-clusters-config
spec:
  generators:
  - matrix:
    generators:
      - git:
        repoURL:
        revision: HEAD
        directories:
          - path: app-clusters-config/*
      - clusters:
          selector:
            matchLabels:
              env: "prod"
  template:
    metadata:
      name: '{{name}}-{{path[0]}}'
    spec:
      project: "admin"
      source:
        repoURL: https://github.com/knee-berts/multi-cluster-gke-argocd/
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{server}}' # 'server' field of the secret
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true