apiVersion: networking.gke.io/v1beta1
kind: MultiClusterIngress
metadata:
  name: asm-ingressgateway-xlb-multicluster-ingress
  namespace: asm-gateways
  annotations:
    networking.gke.io/static-ip: "34.120.90.166"
    networking.gke.io/pre-shared-certs: "mcrt-becb74ff-1d6e-4b89-97df-39818685d57c,mcrt-be2b6380-8b9d-4763-9155-fb12f3bef973"
spec:
  template:
    spec:
      backend:
        serviceName: asm-ingressgateway-xlb-multicluster-svc
        servicePort: 443